spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1999
    url: jdbc:mysql://localhost:3306/db_dianshang?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #    rabbitMQ
mybatis:
  configuration:
    map-underscore-to-camel-case: true #下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
#简洁日志
server:
  servlet:
    session:
      timeout: 120
  port: 8081
#  rabbitMQ